### ISSUE TITLE
About the experimental settings of Table 1

### ISSUE THREAD

**Issue by packer-c** [tsinghua-fib-lab/GPD#1]
Thanks for your nice work and code.
I saw in table 1, you compared four target datasets Washington D.C., Baltimore, LA and Didi-Chengdu and reported some results. But a clearly description of the setting seems to be missing in the paper.

For example, I would like to know when Washington D.C is the target dataset, what is the source dataset? What are the total (input) samples in the source datasets? How many days will it be tested on the target dataset?

Looking forward to your reply. Thanks in advance!

**Comment by PLUTO-SCY** [comment]
Thank you for your interest in our work. 

1. Experimental setup of source city and target city: There are two types of spatio-temporal prediction tasks and two types of corresponding datasets: New York, Washington, D.C. and Baltimore, these 3 datasets are crowd flow datasets. MetaLA, PEMS-Bay, Didi-Chengdu, and Didi-Shenzhen, these 4 datasets are traffic speed datasets. In the transfer task corresponding to each type of datasets, when one dataset is set as the target dataset, the others are set as source datasets. So if  Washington D.C. is set as the target, New York and Baltimore are source datasets. If Didi-Chengdu is set as the target, MetaLA, PEMS-BAy and Didi-Shenzhen are source datasets.
2. The total (input) samples in the source datasets: We used 70% of the total source data, which is enough to train to convergence.
3. How many days will it be tested on the target dataset: 30% of the total target data.

Hope my answer can be of help.

**Comment by packer-c** [comment]
Clear, thanks for your kindly reply!
